blank_issues_enabled: true

contact_links:
  - name: ðŸ§µ Questions & Support
    url: https://github.com/dipexplorer/LegalHuB/discussions
    about: Please use GitHub Discussions for general questions, ideas, or help.
